### PR TITLE
Gl

### PR DESCRIPTION
**Pull request by montaga**
First Version of semi-working GL :)

### CODE REVIEW

**Comment by kranich** [comment]
@montaga Please `git rebase master` to fix the failing Travis CI build.

**Comment by gagern** [comment]
Rebase not neccessary, but we need this beautified. See updated Travis output.

**Comment by montaga** [comment]
Thank you for your hints. Now everything should be fine for merging.

**Comment by strobelm** [comment]
Perhaps we could squash some commits and rebase into master (we could do this together in the office @montaga )

**Comment by gagern** [comment]
Don't squash too much: we should be able to see the core ideas in the development process, and to check out any previous versions which might have worked differently and thus might serve for comparison. Squashing minor fixes and getting rid of non-viable code seems all right and is probably a good idea, but I'd leave substantial code edits intact. Note that rebase has trouble handling merges.

**Comment by strobelm** [comment]
@montaga and i came to terms that the rebase quite tedious, if there are no objections i will merge the branch this evening.

**Pull request merged**
