### PR TITLE
Added a strange function to return a constant list containing strange things

### PR DESCRIPTION
**Pull request by kortenkamp**
This is just for learning how to create a merge request etc. Please ignore this pull request. Thank you.

### CODE REVIEW

**Comment by kranich** [comment]
@kortenkamp This looks wonderful. Could you please add a reftest before we merge this? ;-)

**Comment by kortenkamp** [comment]
per request from @kranich I added a reftest.

**Comment by gagern** [comment]
Despite the reassignment I'll be closing this, as a successful test but not a feature for our master.

**Comment by kortenkamp** [comment]
Ok, too bad. Will try again with substantial features.

**Pull request closed without merging**
