### PR TITLE
Change default text size

### PR DESCRIPTION
**Pull request by gagern**
This changes the default text for `drawtext` from 20 to 12, since that's what Cinderella uses. Adding `drawtext(20)` to the move or draw script (but not the init script!) can restore the old behavior, as was done with the examples.

There is also a new setting `defaultAppearance.textsize` which controls the text size for geometric elements, like labels for points. These could only be set per element so far, with the default being fixed at 12.

@richter-gebert, please have a look at this, either merge it yourself or delegate to e.g. @strobelm if the general approach is OK. And be prepared to change all existing content outside this repository which makes use of `drawtext` with no accompanying `textsize` call or `size->` modifier.

This pull request addresses #49, but doesn't unify the font family yet.

### CODE REVIEW

**Comment by gagern** [comment]
Before I forget it: @richter-gebert decided to not change the default to `12`. So we should uniformly make the default `20`, while explicitely settling on a default of `12` in cooperation with Cinderella. There are several ways how we could achieve this:

1. Use the `cinderella` property stored in the arguments to `createCindy`. This makes the distinction somewhat obscure, which might be confusing for people who copy&paste code from one widget to another.

2. Have Cinderella export its default font size as `defaultAppearance.textsize`. Use that setting as the default for both labels of `geometry` elements and scripted calls to `drawtext`. This is somewhat unprecedented, since so far `defaultAppearance` only affects `geometry`, not script calls. But it has the nice benefit that users can consistently change their font size in a single place.

3. Have Cinderella export `defaultAppearance.textsize` as above, but also have it issue a call to the `textsize(…)` function at the beginning of any `move` or `draw` script it might contain. This will cause trouble if some widget designer decides to overwrite the unary `textsize` function. In our most recent discussion of this issue, this was what @richter-gebert decided to use, but I hadn't thought of the overwrite issue at that time, so I'm no longer certain this is a good idea.

In case compatibility with past versions of CindyJS-Widgets exported from Cinderella is an issue, then 1. is the *only* viable alternative. And even that doesn't work for Cinderella versions which didn't export that setting yet. Luckily, the most recent versions of MC² are converting files on the fly now, so we don't have to worry about those. Currently my personal preference is 2.

**Comment by kranich** [comment]
@gagern As far as I recall, @richter-gebert agreed upon 2. Can this be merged now?

**Comment by gagern** [comment]
@kranich: The code as it stands does not implement 2., so it needs to be re-implemented before getting merged.

**Comment by gagern** [comment]
Closing in favor of #345 which takes approach 2.

**Pull request closed without merging**
