### PR TITLE
faster center of conic

### PR DESCRIPTION
**Pull request by strobelm**
This pull request removes an unnecessary matrix-vector multiplication in the center of conic routine.

### CODE REVIEW

**Comment by kranich** [comment]
@strobelm I find the following a bit clearer:
```JavaScript
var adj = List.adjoint3(c);
// return General.mult(adj, List.linfty);
// do not use matrix vector multiplication, we know the result
return {
     'ctype': 'list',
     'value': [adj.value[2].value[0], adj.value[2].value[1], adj.value[2].value[2]]
};
```

Would you mind to change this?

**Comment by strobelm** [comment]
Not at all, it' done. By the way this is about 3 times faster than the
previous version.

Am 13.04.2016 um 17:07 schrieb Stefan Kranich:
>
> @strobelm <https://github.com/strobelm> I find the following a bit
> clearer:
>
> var adj = List.adjoint3(c);
> // return General.mult(adj, List.linfty);
> // do not use matrix vector multiplication, we know the result
> return {
>      'ctype': 'list',
>      'value': [adj.value[2].value[0], adj.value[2].value[1], adj.value[2].value[2]]
> };
>
> Would you mind to change this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CindyJS/CindyJS/pull/325#issuecomment-209497910>
>

-- 
Michael Strobel, M.Sc.

Technische Universität München -- Zentrum Mathematik
Lehrstuhl für Geometrie und Visualisierung (M10)
Boltzmannstr. 3, 85747 Garching bei München 
https://www-m10.ma.tum.de/bin/view/Lehrstuhl/MichaelStrobel

**Comment by kranich** [comment]
@strobelm Thanks.

**Comment by gagern** [comment]
While you are at it, note that the third column of the adjoint matrix the same as the cross product of the first two columns of the original matrix. Or in more geometric words, the pole of the line at infinity is the intersection of the polar of two distinct points at infinity, like (1,0,0) and (0,1,0). This should shorten the operation by yet another few unneccessary computations.

But in the long run I'd like to have some machinery which automatically removes all those unneccessary computations so that you can write readable high-level descriptions of operations without incurring unneccessary costs. Still way to go in that direction, though.

**Pull request merged**
