### PR TITLE
Implement 'keys' operator

### PR DESCRIPTION
**Pull request by strobelm**
This implements the 'keys' operator for colon dictionaries.

### CODE REVIEW

**Comment by montaga** [comment]
Thank you!
Unfortunately, the code
`
forall(keys(A), k,
  errc(k + ": " + A:k)
);
`
does not work. However, if one uses `return General.string(k);` instead of `return General.string('"' + k + '"');`, then it works. Should we change it like that?

**Comment by montaga** [comment]
I checked it with the current release of Cinderella, and yes, there are also no `"`s. So I will change this...

**Comment by strobelm** [comment]
Ah nice catch! I deliberately changed it since the documentation states that there should be double quotes.

**Comment by strobelm** [comment]
Should be fixed now.

**Comment by montaga** [comment]
thanks :)

**Pull request merged**
