### PR TITLE
fix travis env for c++11

### PR DESCRIPTION
**Pull request by strobelm**
Hi, according to https://github.com/travis-ci/travis-ci/issues/4771#issuecomment-241439984 this should fix our travis problems.

### CODE REVIEW

**Comment by kranich** [comment]
libsass compilation takes ages! Maybe we should use [less](https://www.npmjs.com/package/less) instead?

**Comment by strobelm** [comment]
superseded by #607

**Comment by gagern** [comment]
As for sass vs. less: I prefer the sass language slightly, but the feeling is not strong enough to rule out less.

In what situations would you encounter rebuilds? I see them for Travis builds against latest version of Node, but that's mainly because we are using an outdated version of libsass. Instead of movinbg to less, I'd just bump the sass module so we can use a binary release there.

**Comment by kranich** [comment]
Yes, for Travis builds with latest Node. If a newer sass version speeds up the build process significantly, I would appreciate that very much.

**Pull request closed without merging**
