### PR TITLE
assign code to user fields of objects and lists

### PR DESCRIPTION
**Pull request by kortenkamp**
This commit should provide compatibility between CindyJS and Cinderella. In Cinderella it is possible to assign code not only to a variable, but also to a user field:
```
A:"draw" := draw(A,A+(1,1));
```
This code can be called using 
```
A:"draw";
````

### CODE REVIEW

**Comment by strobelm** [comment]
Hi! Any reason why we cannot call `evaluateAndVal`? Then we could simplify the code a bit.

**Comment by strobelm** [comment]
And thanks for implementing this!

**Comment by kortenkamp** [comment]
> Hi! Any reason why we cannot call `evaluateAndVal`? Then we could simplify the code a bit.

Yes: This causes the assignment of code to a UserData field to be executed, which is the wrong semantics. That is the reason why I had to create new code.

However, this is still work in progress.

**Comment by kortenkamp** [comment]
I just hope I did not mess up too much code… I will check then main branch again after this.

**Pull request merged**
