### PR TITLE
update to closure compiler 20180506

### PR DESCRIPTION
**Pull request by strobelm**
We haven't updated the closure compiler for quite a while and it also contains improvements for object literals (which we use heavily). See https://github.com/google/closure-compiler/wiki/Releases#september-10-2017-v20170910

### CODE REVIEW

**Comment by kranich** [comment]
The decision back then was to update Closure Compiler just once in awhile, when it has changes that we benefit from.

**Comment by kranich** [comment]
Apparently, unlike with a lower node version, in `tools/prepare-deploy.js` the dependencies in `lib` and `node_modules` were prefixed with `build/js`. I have not found out what caused this, so I am not sure if 
d6fed5b is the proper fix.

@strobelm What do you think?

**Comment by kranich** [comment]
There are some (new?) Closure Compiler warnings for CindyJS. Maybe we can address these as well while we are at it?

**Comment by strobelm** [comment]
Oh I completely forgot about this PR. The fix looks fine to me. Thanks a lot @kranich!

**Pull request merged**
