### PR TITLE
Allow setting the fillcolor of buttons

### LINKED ISSUE #510: Textbuttons should support Colors
Buttons are currently gray. In Cindy they have colors.

### PR DESCRIPTION
**Pull request by gagern**
This fixes #510.

I've decided to move the type-specific accessors to GeoOps, so that we don't clutter Accessors with a lot of type-specific functionality. Let me know whether you consider this a good move.

### CODE REVIEW

**Comment by strobelm** [comment]
I somehow feel uneasy with functions changing the display of an object in geoOps, mixing model and view is usually bad practice. Perhaps i am to pedantic here, any further opinions?

**Comment by kortenkamp** [comment]
I don't think that the color is a property of the view, but of the model, indeed. Quick example: If you change the coordinates of a line, it's view will change as well, but we – hopefully – agree on the fact that the coordinates are a model property. 

The color is a property of text buttons, and how to interpret them is depending on the view, yes. But it belongs into geoOps, I grew with @gagern .

**Comment by gagern** [comment]
When moving the accessors to GeoOps I also had some less appearance-related accessors in mind. Namely #509 requires a read/write `.angle` property for `PointOnCircle` which will likely cloely resemble some of the functionality we have in existing `PointOnCircle` methods. And I guess there will be more accessors like these.

**Comment by strobelm** [comment]
Alright i'm sufficiently convinced. The code looks fine. Merged.

**Pull request merged**
