### PR TITLE
Only run mouseclick if the courser has not moved too far

### PR DESCRIPTION
**Pull request by montaga**
With this PR, mouseclick in CindyJS be handeled as it is in Cinderella: If the mouse is moved some distance while having a button pressed, then the mouseclick-script will not be evoked.

Before that, the mouseclick-event coincided with the mouseup-event in almost every case.

### CODE REVIEW

**Comment by kortenkamp** [comment]
Ah, this reminds me of a problem I noticed – is it possible that mouse click is never invoked on tablets? At least I had to move my code from click to up in order to make the same construction work on the iPad.

**Comment by strobelm** [comment]
Shouldn't be ```hasmoved``` somewhere be reset to false?

**Comment by montaga** [comment]
@strobelm : `hasmoved = false;` is executed with the `mousedown`-event.

@kortenkamp : Thank you for this remark :-) With the last commit, "mouseclick" should also work for iPad (as it is the case with the other mouse-events, there is no support for multi-touch yet)

**Comment by kortenkamp** [comment]
Great - thank you for adding that. As for multitouch: I would like to discuss this, as I put some thought into the implementation in Cinderella (the Java version) of multitouch and its integration with CindyScript. Maybe we should try to setup a video conference?

**Comment by strobelm** [comment]
Thanks!

**Pull request merged**
